### ISSUE TITLE
[feature request] Docker

### ISSUE THREAD

**Issue by JourneyOver** [markogrbic/py-steamgifts-bot#1]
Pretty much title.. Thought it would be something nice to have for a project like this.

**Comment by markogrbic** [comment]
Thanks for the suggestion I’ll add it to the next release.

**Comment by markogrbic** [comment]
Dockerfile was added to the latest release [v0.2.0](https://github.com/markogrbic/py-steamgifts-bot/releases/tag/v0.2.0).

**Comment by JourneyOver** [comment]
@markogrbic can I get any information on how to run this as you did not provide any information at all in your readme for it, is there a volume path? Env variables that I can set instead? or what??? I've tried setting a volume to `/app` but it throws an error about not being able to find the `./main.py`

**Comment by markogrbic** [comment]
@JourneyOver I have updated the README.md with the information on how to run the bot via Docker.

Generally you position yourself in the root folder after downloading and unzipping it and run the following commands:
```
sudo docker build -t pysgbot .
sudo docker run -d -e PYTHONUNBUFFERED=1 pysgbot
```

Please see README.md for details and let me know if something is still unclear or if you're having issues. I suggest that you download the latest tagged release as of now which is 0.2.2.

Hope it's more clear now.
